# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1leGA_vApqpIQnwLgEMNy5LR7VI6tvwv1
"""

!pip install opencv-python torch
!pip install transformers
#clone YOLOv5 and
!git clone https://github.com/ultralytics/yolov5  # clone repo
%cd yolov5
%pip install -qr requirements.txt # install dependencies
%pip install -q roboflow

import torch
import os
from IPython.display import Image, clear_output  # to display images

print(f"Setup complete. Using torch {torch.__version__} ({torch.cuda.get_device_properties(0).name if torch.cuda.is_available() else 'CPU'})")

!pip install opencv-python-headless
from IPython.display import HTML
import io
import base64
from IPython.display import display
from IPython.display import HTML
import io
import base64
from IPython.display import display

import glob
from IPython.display import Image, display
from IPython.display import Video, display
from IPython.display import HTML
import os 


def show_video(file_path, width=640, height=480):
    video_encoded = base64.b64encode(io.open(file_path, 'rb').read())
    return HTML(data='''<video width="{0}" height="{1}" alt="test" controls>
                      <source src="data:video/mp4;base64,{2}" type="video/mp4" />
                      </video>'''.format(width, height, video_encoded.decode('ascii')))

my_image = '/content/drive/MyDrive/demo_dogs/몽실이.mov'
result = !python detect.py --weights '/content/drive/MyDrive/yolov5best.pt' --img 416 --conf 0.1 --source {my_image}

file_extension = os.path.splitext(my_image)[1].lower()
pd = '이 강아지는 푸들입니다. \n푸들은 흰색, 갈색, 검은색 등 다양한 색의 곱슬곱슬한 털이 동그랗게 말린 형태를 보입니다. \n큰 순서부터 차례대로 스탠다드 푸들, 미디엄 푸들, 미니어쳐 푸들, 토이 푸들의 4종류가 있습니다. \n가장 큰 스탠다드 푸들은 45-60cm의 큰 체구를, 토이푸들은 25cm 정도의 작은 체구를 가집니다. \n푸들은 주인에 대한 애정도와 충성심이 깊기로 유명합니다. \n이 때문에 종종 분리불안을 겪기도 해 보호자의 훈련이 필요합니다. \n감정표현이 풍부하며 똑똑하고 학습 능력이 뛰어납니다. \n푸들은 본래 사람과 함께 사냥에 나서던 조렵견이어서 수영을 잘하고 활동량이 높은 편입니다. \n털이 잘 빠지진 않지만 곱슬곱슬한 털이 엉키지 않도록 관리가 필요합니다. \n푸들은 피부염과 슬개골 탈구, 백내장 등의 유전병에 주의해야합니다.'
ms = '이 강아지는 말티즈입니다. \n말티즈는 희고 긴 털을 가지고 있고 체고는 19~25cm이며, 몸무게는 2.7~4kg 정도의 소형견입니다. \n말티즈는 활발하고 활동량이 많아 놀이와 산책을 좋아합니다. \n사람을 좋아하고 잘 따르는 다정다감한 성격을 가지고 있어 훈련과 교육을 쉽게 할 수 있습니다. \n말티즈의 고향은 지중해의 몰타섬으로 알려져 있습니다. \n희고 고운 털을 가지고 있지만 눈물과 침에 쉽게 변색되고 잘 엉켜서 보호자의 관리가 필요하기도 합니다. \n잘 걸리는 유전병에는 슬개골 탈구, 심장질환 등이 있어 건강관리에 유의해야합니다.'
ch ='이 강아지는 푸들입니다. \n치와와는 작은 얼굴에 커다란 눈의 귀여운 외모를 가지고 있습니다. \n22cm이하의 체고, 몸무게는 2.7kg 이하로 세계에서 가장 작은 견종으로 알려져있습니다. \n털은 장모의 롱타입과 장모의 스무스타입으로 나뉩니다. \n치와와는 승부욕이 강한 성격을 가지고 있습니다. \n에너지와 경계심이 높아서 다른 개들에게 싸우려 하기도 합니다. \n하지만 반려인에게는 애착이 강하고 잘 따릅니다. \n치와와는 예민한 성격 때문에 사회화 훈련이 필요한 편입니다. \n치와와는 따뜻한 중남미에서 살던 견종이기 때문에 추위에 매우 민감합니다. \n때문에 따뜻한 옷은 필수이고 겨울에는 산책에 주의해야합니다. \n몸집이 작아 골절과 탈구 등 골격계 질병과 사고에 유의해야합니다.'
sh = '이 강아지는 시츄입니다. \n시츄는 주로 흰색과 다른 색이 섞인 파티 컬러의 긴 털을 가지고 있습니다. \n체고는 27cm이하, 체중은 4.5~8kg 정도의 소형견에 속합니다. \n큰 눈과 둥근 얼굴의 <국화 얼굴> 이라 불리는 귀여운 외모를 가지고 있습니다. \n시츄는 주로 원만하고 조용한 성격을 가지고 있습니다. \n짖음이 적고 애교가 많아 아이들과도 잘 지내고 초보 견주가 키우기에 적합하기도 합니다. \n시츄는 티벳에서 유래해 중국 왕실에서 사랑받던 견종입니다. \n오랫동안 랩독으로 자라 활동량이 많지는 않은 편입니다. \n눈이 크고 돌출되어 있는 편이기 때문에 안구 질환에 유의해야 합니다.'
po = '이 강아지는 포메라니안입니다. \n포메라니안은 붉은색, 흰색, 검은색 등 다양한 색의 풍성한 이중모를 가지고 있습니다. \n귀와 주둥이가 뾰족하고 체고는 28cm 이하, 체중은 1.8~2.8kg 정도의 소형견입니다. \n포메라니안은 발랄하고 호기심이 많은 성격을 가지고 있습니다. \n에너지가 넘치고 예민한 면이 있어 자주 짖기도 하기 때문에 보호자의 훈련이 필요합니다. \n포메라니안은 스피츠 계열의 견종으로, 유럽이 고향으로 알려져있습니다. \n이중모를 가지고 있기 때문에 털이 잘 빠지는 편이며 털 관리를 자주 해주어야합니다. \n작고 귀여운 외모로 오래 전부터 유럽 왕실의 사랑을 받기도 했습니다.'


# Process each line of the YOLOv5 detection results
for line in result:
    # Check if the line contains information for the desired class ("Standard_Poodle")
    if "Poodle" in line:
         print(pd)
         for imageName in glob.glob('/content/drive/MyDrive/qr_image/푸들.JPG'): #assuming JPG
              display(Image(filename=imageName, width=120, height=144 ))
              print("\n")
         break
    elif "Maltese" in line:
         print(ms)
         for imageName in glob.glob('/content/drive/MyDrive/qr_image/말티즈.JPG'): #assuming JPG
              display(Image(filename=imageName, width=120, height=144 ))
              print("\n")
         break
    elif "Chihuahua" in line:
          print(ch)
          for imageName in glob.glob('/content/drive/MyDrive/qr_image/치와와.JPG'): #assuming JPG
              display(Image(filename=imageName,width=120, height=144 ))
              print("\n")
          break
    elif "Shih-Tzu" in line:
          print(sh)
          for imageName in glob.glob('/content/drive/MyDrive/qr_image/시츄.JPG'): #assuming JPG
              display(Image(filename=imageName, width=120, height=144 ))
              print("\n")
          break
    elif "Pomeranian" in line:
          print(po)
          for imageName in glob.glob('/content/drive/MyDrive/qr_image/포메라니안.JPG'): #assuming JPG
              display(Image(filename=imageName,width=120, height=144 ))
              print("\n")
          break

import glob
from IPython.display import Image, display
from IPython.display import Video, display

if file_extension == '.jpg' or file_extension == '.jpeg':
    for imageName in glob.glob('/content/yolov5/runs/detect/exp*/*.JPG'): #assuming JPG
        display(Image(filename=imageName, width = 240 , height= 288))
else:
    video_files = glob.glob('/content/yolov5/runs/detect/exp*/*.mp4')

    if video_files:
        display(show_video(video_files[0]))
